### ISSUE TITLE
E: Unable to locate package libopen3d-dev

### ISSUE THREAD

**Issue by Salima-Bourbia** [rafael2k/bitdance-pc_metric#2]
Hello, 

Please, I want to try your code but when I tried to install libopen3d-dev, I always got this error:  **E: Unable to locate package libopen3d-dev**. Otherwise, could you tell me which command you use to execute your code?

Thank you.

**Comment by rafael2k** [comment]
I can not read your mind, much less your operational system documentation. Please read the README again.

**Comment by Salima-Bourbia** [comment]
As you mentioned in your README: I tried to install the Open3D library and the other dependencies using your suggested command: **sudo apt-get install libopen3d-dev libeigen3-dev libpng-dev  zlib1g-dev**. But I got this error 
![image](https://user-images.githubusercontent.com/48332731/200200564-5b0541ff-84cd-4b17-8bae-e34ebcf3e229.png)

**Comment by rafael2k** [comment]
Read a bit more of the README. You are not there yet.

**Comment by rafael2k** [comment]
At least read the "Compilation" section. COME ON!

**Comment by rafael2k** [comment]
... "compiled and tested on Debian Linux 11 (codename Bullseye) and Ubuntu 22.04 LTS."
